### ISSUE TITLE
Decision files can cause errors?

### ISSUE THREAD

**Issue by Manouchehri** [uds-se/FormatFuzzer#6]
Related to #5.

## Checklist

- [X] I have included the [relevant portions of the] 010 template used that caused the bug
- [X] I have filled out the environment section

## Environment

**Platform** 

- [ ] Windows
- [ ] Mac
- [X] Linux
- [ ] Other (please specify)

**Python Version**

- [ ] Python 2.7
- [ ] Python 3.4
- [ ] Python 3.5
- [X] Python 3.6
- [ ] Python 3.7
- [ ] Python 3.8
- [ ] Other (please specify)

## Describe the bug

When mutating the decision files randomly, quite often FormatFuzzer will fail on `random size exceeded rand_size`.

I also run into `bitfield lookahead not implemented` sometimes.

## To Reproduce

Steps to reproduce
```
while true; do ./gif-fuzzer fuzz --decision /dev/urandom /dev/null ; done
```

## Expected Behavior

```
gif-fuzzer: output.gif created
```

Is this an intended design limitation/choice, or a bug? I think it's the former, but it's not documented anywhere.

**Comment by RafaelTupynamba** [comment]
That's due to a bug, should be fixed now.

**Comment by Manouchehri** [comment]
You're awesome.

**Comment by Manouchehri** [comment]
Hmm, I applied 81799fff004078b13368ad788ba4af479012b626, but I still end up with a few errors when running in a loop.

```
Warning: File is not a valid GIF. Template stopped.
Template exited with code -1
```

**Comment by Manouchehri** [comment]
And I actually sadly still get the same error as before in my fuzzer. :( 

```
Error: random size exceeded rand_size
```

**Comment by Manouchehri** [comment]
Ah, so this is due to the template. Not a bug in FormatFuzzer, it's working as intended.

https://github.com/uds-se/FormatFuzzer/blob/b37f66ff40f5aa28291e0ef1328737022a937ff5/templates/gif.bt#L85
